---
title: "Stats 100: Project - NHL"
author: "Niall Kehoe"
date: "05/11/2023"
header-includes:
   - \usepackage{bbm, amsmath,amsfonts,amsthm,amssymb,mathrsfs,amsxtra,amscd,latexsym, xcolor, graphicx, fvextra}
   - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output: pdf_document
---

\newcommand{\Var}{\mathrm{Var}}

```{r}
suppressPackageStartupMessages(library(knitr)) #makes pdfs
suppressPackageStartupMessages(library(latex2exp))
suppressPackageStartupMessages(library(ggplot2)) #makes nice plots
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(glmnet))
suppressPackageStartupMessages(library(predtools))
suppressPackageStartupMessages(library(psych))
knitr::opts_chunk$set(echo = TRUE)

# Checks if package is installed, installs if necessary, and loads package for current session

pacman::p_load(
  lubridate,  # general package for handling and converting dates  
  parsedate,   # has function to "guess" messy dates
  aweek,      # another option for converting dates to weeks, and weeks to dates
  zoo,        # additional date/time functions
  tidyverse,  # data management and visualization  
  rio)        # data import/export
```

# Acknowledgements

NO ACKNOWLEDGEMENTS

# EPL

```{r}

dollarToInteger <- function(amount) {
  # Remove dollar sign and commas
  amount <- gsub("\\$|,", "", amount)
  
  # Convert to integer
  amount <- as.integer(amount)
  
  return(amount)
}

readInSalaries<- function(year) {
  filename <- paste0("NHL/Salaries/NHL Salaries - ", year, ".csv")
  salaries = read.csv(filename)
  
  salaries$Salaries = dollarToInteger(salaries$TOTAL) / 1000000
  # salaries$Salaries = dollarToInteger(salaries$X2022.TOTAL.PAYROLL) / 1000000
  
  salaries$Team = convertNHLName(salaries$TEAM)
  
  return (salaries)
}

```

```{r}


convertNHLName <- function(name) {
  new_name <- gsub(" FC", "", name)
  # new_name <- gsub(" United", " Utd", new_name)
  # new_name <- gsub("é", "e", new_name)
  # new_name <- gsub(" SC", "", new_name)
  # new_name <- gsub("Houston ", "", new_name)
  # new_name <- gsub("New York City", "NYCFC", new_name)
  # new_name <- gsub("New England Revolution", "New England", new_name)
  # new_name <- gsub("New York Red Bulls", "NY Red Bulls", new_name)
  # new_name <- gsub("Philadelphia Union", "Philadelphia", new_name)
  # new_name <- gsub("San Jose Earthquakes", "San Jose", new_name)
  # 
  # 
  # new_name <- gsub("Seattle Sounders", "Seattle", new_name)
  # new_name <- gsub("Sporting Kansas City", "Sporting KC", new_name)
  # new_name <- gsub("Vancouver Whitecaps", "Vancouver", new_name)
  # new_name <- gsub("Los Angeles Galaxy", "LA Galaxy", new_name)
  # new_name <- gsub("San Jose Clash", "San Jose", new_name)
  	

  return (new_name)
}

readInResults <- function(year) {
  filename <- paste0("NHL/season/NHL Results - ", year, ".csv")
  data = read.csv(filename)
  data$Squad = convertMLSName(data$Name)
  # data <- slice(data, 1:(n() - 2))
  # data <- data[order(data$R,decreasing=TRUE),]
  # data <- data[order(data$TEAM,decreasing=FALSE),]
  data <- data[order(data$Squad), ]

  salaries = readInSalaries(year)
  # View(salaries)

  # Merge based on 'Team' and 'Tm' columns
  merged_df <- merge(data, salaries, by.x = "Squad", by.y = "Team", all = TRUE)

  # Adding in more data over time, by normalising based on that years average

  # merged_df <- merged_df[, !(names(merged_df) %in% c("Notes", "Last.5"))]
  
  # merged_df <- merged_df[, -which(names(merged_df) == "Last.5")]
  
  # Drop NA values
  merged_df <- na.omit(merged_df)
  
  merged_df$Squad = paste0(merged_df$Squad, "-", year)
  
  # Normalise Salaries - convert it to a z-score
  merged_df$Salaries.Norm = (merged_df$Salaries - mean(merged_df$Salaries)) / mean(merged_df$Salaries)
  merged_df$W.Norm = (merged_df$W - mean(merged_df$W)) / mean(merged_df$W)
  merged_df$PTS.Norm = (merged_df$PTS - mean(merged_df$PTS)) / mean(merged_df$PTS)
  
  
  merged_df$WIN. = merged_df$W / merged_df$GP
  merged_df$WIN.Norm = (merged_df$WIN. - mean(merged_df$WIN.)) / mean(merged_df$WIN.)

  return(merged_df)
}

year = 2022
# mlb2021 = readInResults(year)

nhl2022 = readInResults(year)
View(nhl2022)


```

```{r}
plot(x = nhl2022$Salaries, y = nhl2022$W,
   xlab = "Salaries (millions)",
   ylab = "Performance by Total Runs",	 
   main = "Salaries vs Performance"
)
abline(lm(nhl2022$W ~ nhl2022$Salaries), col='blue')

plot(x = nhl2022$Salaries, y = nhl2022$PTS,
   xlab = "Salaries (millions)",
   ylab = "Performance by Total Runs",	 
   main = "Salaries vs Performance"
)
abline(lm(nhl2022$PTS ~ nhl2022$Salaries), col='blue')

```

```{r}



# plot(x = log(merged_df_2022$Salaries), y = merged_df_2022$W,
#    xlab = "Salaries (millions)",
#    ylab = "Performance by Total Runs",	 
#    main = "log(Salaries) vs Performance"
# )
# abline(lm(merged_df_2022$W ~ log(merged_df_2022$Salaries)), col='blue')
```

```{r}


model1 = lm(W ~ Salaries, data = nhl2022)
summary(model1)

model2 = lm(PTS ~ Salaries, data = nhl2022)
summary(model2)


```

```{r}



```

```{r}

# plot(x = mlb2021$Salaries.Norm, y = mlb2021$R.Norm,
#    xlab = "Salaries (millions)",
#    ylab = "Performance by Total Runs",	 
#    main = "Salaries vs Performance"
# )
# abline(lm(mlb2021$R.Norm ~ mlb2021$Salaries.Norm), col='red')
```

```{r}

nhl2022 = readInResults(2022)
nhl2021 = readInResults(2021)
nhl2020 = readInResults(2020)
nhl2019 = readInResults(2019)
nhl2018 = readInResults(2018)
nhl2017 = readInResults(2017)
nhl2016 = readInResults(2016)
nhl2015 = readInResults(2015)
nhl2014 = readInResults(2014)
nhl2013 = readInResults(2013)

combined_df <- data.frame()

# Add rows from df1, df2, and df3 to combined_df
combined_df <- rbind(combined_df, nhl2022)
combined_df <- rbind(combined_df, nhl2021)
combined_df <- rbind(combined_df, nhl2020)
combined_df <- rbind(combined_df, nhl2019)
combined_df <- rbind(combined_df, nhl2018)
combined_df <- rbind(combined_df, nhl2017)
combined_df <- rbind(combined_df, nhl2016)
combined_df <- rbind(combined_df, nhl2015)
combined_df <- rbind(combined_df, nhl2014)
combined_df <- rbind(combined_df, nhl2013)

# Print the combined data frame
View(combined_df)
```

```{r}


plot(x = combined_df$Salaries.Norm, y = combined_df$W,
   xlab = "Salaries (millions)",
   ylab = "Performance by Wins",	 
   main = "Salaries vs Performance"
)
abline(lm(combined_df$W ~ combined_df$Salaries.Norm), col='red')
```

```{r}

model = lm(W ~ Salaries.Norm, data = combined_df)
summary(model)
```

```{r}


# must exclude covid year for this to work
plot(x = combined_df$Salaries, y = combined_df$W,
   xlab = "Salaries (millions)",
   ylab = "Performance by Total Runs",	 
   main = "Salaries vs Performance"
)
abline(lm(combined_df$W ~ combined_df$Salaries), col='red')
```

```{r}

plot(x = combined_df$Salaries.Norm, y = combined_df$W.Norm,
   xlab = "Salaries (millions)",
   ylab = "Performance by Win Normalised",	 
   main = "Salaries vs Performance"
)
abline(lm(combined_df$W.Norm ~ combined_df$Salaries.Norm), col='red')


model = lm(W.Norm ~ Salaries.Norm, data = combined_df)
summary(model)
```

```{r}

plot(x = combined_df$Salaries.Norm, y = combined_df$PTS,
   xlab = "Salaries (millions)",
   ylab = "Performance by Total Runs",	 
   main = "Salaries vs Performance"
)
abline(lm(combined_df$PTS ~ combined_df$Salaries.Norm), col='red')

plot(x = combined_df$Salaries.Norm, y = combined_df$PTS.Norm,
   xlab = "Salaries (millions)",
   ylab = "Performance by Total Runs",	 
   main = "Salaries vs Performance"
)
abline(lm(combined_df$PTS.Norm ~ combined_df$Salaries.Norm), col='red')



model = lm(PTS ~ Salaries.Norm, data = combined_df)
summary(model)
model = lm(PTS.Norm ~ Salaries.Norm, data = combined_df)
summary(model)


```

```{r}


# combined_df$WIN. = combined_df$W / combined_df$GP
# combined_df$WIN.Norm = (combined_df$WIN. - mean(combined_df$WIN.)) / mean(combined_df$WIN.)

plot(x = combined_df$Salaries.Norm, y = combined_df$WIN.Norm,
   xlab = "Salaries (millions)",
   ylab = "Performance by Win%",	 
   main = "Salaries vs Performance"
)
abline(lm(combined_df$WIN.Norm ~ combined_df$Salaries.Norm), col='red')


model = lm(WIN.Norm ~ Salaries.Norm, data = combined_df)
summary(model)

```

```{r}


plot(x = combined_df$Salaries, y = combined_df$W,
   xlab = "Salaries (standardized)",
   ylab = "Performance by Wins",	 
   main = "Salaries vs Performance"
)
abline(lm(combined_df$W ~ combined_df$Salaries), col='red')

model = lm(W ~ Salaries, data = combined_df)
summary(model)

```

## Team Total Spending

```{r}


plot(x = combined_df$Salaries.Norm, y = combined_df$WIN.Norm,
   xlab = "Salaries (standardized)",
   ylab = "Performance by Win% (standardized)",	 
   main = "Salaries vs Performance"
)
abline(lm(combined_df$WIN.Norm ~ combined_df$Salaries.Norm), col='red')


model = lm(WIN.Norm ~ Salaries.Norm, data = combined_df)
summary(model)

```

```{r}


```

```{r}

```

```{r}

```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```
