---
title: "Stats 100: Project - MLB"
author: "Niall Kehoe"
date: "05/11/2023"
header-includes:
   - \usepackage{bbm, amsmath,amsfonts,amsthm,amssymb,mathrsfs,amsxtra,amscd,latexsym, xcolor, graphicx, fvextra}
   - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output: pdf_document
---

\newcommand{\Var}{\mathrm{Var}}

```{r}
suppressPackageStartupMessages(library(knitr)) #makes pdfs
suppressPackageStartupMessages(library(latex2exp))
suppressPackageStartupMessages(library(ggplot2)) #makes nice plots
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(glmnet))
suppressPackageStartupMessages(library(predtools))
suppressPackageStartupMessages(library(psych))
knitr::opts_chunk$set(echo = TRUE)

# Checks if package is installed, installs if necessary, and loads package for current session

pacman::p_load(
  lubridate,  # general package for handling and converting dates  
  parsedate,   # has function to "guess" messy dates
  aweek,      # another option for converting dates to weeks, and weeks to dates
  zoo,        # additional date/time functions
  tidyverse,  # data management and visualization  
  rio)        # data import/export
```

# Acknowledgements

NO ACKNOWLEDGEMENTS

# Bradley-Terry Ratings

```{r}

#df_final = read.csv("NBA_2022_23_3pdata_final.csv")
mlb2022 = read.csv("mlb2022.csv") #%>% filter(Date > )

#Removing last row MLB as it is totals
mlb2022 <- slice(mlb2022, 1:(n() - 2)) 
mlb2022 <- mlb2022[order(mlb2022$R,decreasing=TRUE),]

# IDEA:
# or use win # as WELL!

View(mlb2022)


```

```{r}

salaries =  read.csv("MLB-Salaries-2022.csv")

dollarToInteger <- function(amount) {
  # Remove dollar sign and commas
  amount <- gsub("\\$|,", "", amount)
  
  # Convert to integer
  amount <- as.integer(amount)
  
  return(amount)
}

salaries$Salaries = dollarToInteger(salaries$X2022.TOTAL.PAYROLL) / 1000000
# salaries$Salaries = as.numeric(gsub("\\$", "", salaries$Salaries))
# salaries$Salaries = salaries$Salaries / 1000000
View(salaries)

plot(x = salaries$Salaries, y = salaries$WIN.,
   xlab = "Salaries (millions)",
   ylab = "Performance by WIN %",	 
   main = "Salaries vs Performance"
)

plot(x = log(salaries$Salaries), y = salaries$WIN.,
   xlab = "Salaries (millions)",
   ylab = "Performance by WIN %",	 
   main = "log(Salaries) vs Performance"
)
```

```{r}

```

```{r}

# Merge based on 'Team' and 'Tm' columns
merged_df_2022 <- merge(mlb2022, salaries, by.x = "Tm", by.y = "TEAM", all = TRUE)

# Print the merged data frame
#View(merged_df_2022)


plot(x = merged_df_2022$Salaries, y = merged_df_2022$R,
   xlab = "Salaries (millions)",
   ylab = "Performance by Total Runs",	 
   main = "Salaries vs Performance"
)
abline(lm(merged_df_2022$R ~ merged_df_2022$Salaries), col='blue')

plot(x = log(merged_df_2022$Salaries), y = merged_df_2022$R,
   xlab = "Salaries (millions)",
   ylab = "Performance by Total Runs",	 
   main = "log(Salaries) vs Performance"
)
abline(lm(merged_df_2022$R ~ log(merged_df_2022$Salaries)), col='blue')
```

```{r}


model1 = lm(R ~ Salaries, data = merged_df_2022)
summary(model1)

model2 = lm(R ~ log(Salaries), data = merged_df_2022)
summary(model2)


```

```{r}


readInSalaries<- function(year) {
  filename <- paste0("MLB/MLB Salaries - ", year, ".csv")
  salaries = read.csv(filename)
  
  salaries$Salaries = dollarToInteger(salaries$TOTAL.PAYROL) / 1000000
  # salaries$Salaries = dollarToInteger(salaries$X2022.TOTAL.PAYROLL) / 1000000
  return (salaries)
}

readInResults <- function(year) {
  filename <- paste0("MLB/mlb", year, ".csv")
  data = read.csv(filename)
  data <- slice(data, 1:(n() - 2)) 
  data <- data[order(data$R,decreasing=TRUE),]
  
  salaries = readInSalaries(year)
  
  # Merge based on 'Team' and 'Tm' columns
  merged_df <- merge(data, salaries, by.x = "Tm", by.y = "TEAM", all = TRUE)
  merged_df$Tm = paste0(merged_df$Tm, "-", year)
  
  # Adding in more data over time, by normalising based on that years average
  
  # Normalise Salaries
  merged_df$Salaries.Norm = merged_df$Salaries / mean(merged_df$Salaries)
  merged_df$R.Norm = merged_df$R / mean(merged_df$R)

  return(merged_df)
}

year = 2022
mlb2021 = readInResults(year)
View(mlb2021)

```

```{r}

plot(x = mlb2021$Salaries.Norm, y = mlb2021$R.Norm,
   xlab = "Salaries (millions)",
   ylab = "Performance by Total Runs",	 
   main = "Salaries vs Performance"
)
abline(lm(mlb2021$R.Norm ~ mlb2021$Salaries.Norm), col='red')
```

```{r}



mlb2022 = readInResults(2022)
mlb2021 = readInResults(2021)
mlb2020 = readInResults(2020)

combined_df <- data.frame()

# Add rows from df1, df2, and df3 to combined_df
combined_df <- rbind(combined_df, mlb2022)
combined_df <- rbind(combined_df, mlb2021)
combined_df <- rbind(combined_df, mlb2020)

# Print the combined data frame
View(combined_df)
```

```{r}


plot(x = combined_df$Salaries.Norm, y = combined_df$R.Norm,
   xlab = "Salaries (millions)",
   ylab = "Performance by Total Runs",	 
   main = "Salaries vs Performance"
)
abline(lm(combined_df$R.Norm ~ combined_df$Salaries.Norm), col='red')
```

```{r}

model = lm(R.Norm ~ Salaries.Norm, data = combined_df)
summary(model)
```

## Team Total Spending

```{r}

readInSalaries2<- function(year) {
  filename <- paste0("MLB/salaries-2/salaries", year, ".csv")
  salaries = read.csv(filename)
  
  salaries$Salaries = dollarToInteger(salaries$last.yr.payroll) / 1000000
  # salaries$Salaries = dollarToInteger(salaries$X2022.TOTAL.PAYROLL) / 1000000
  return (salaries)
}

readInResults2 <- function(year) {
  filename <- paste0("MLB/mlb", year, ".csv")
  data = read.csv(filename)
  data <- slice(data, 1:(n() - 2))
  data <- data[order(data$R,decreasing=TRUE),]
  
  salaries = readInSalaries2(year)
  
  # Merge based on 'Team' and 'Tm' columns
  merged_df <- merge(data, salaries, by.x = "Tm", by.y = "team.name", all = TRUE)
  merged_df$Tm = paste0(merged_df$Tm, "-", year)
  
  # Adding in more data over time, by normalising based on that years average
  
  # Normalise Salaries
  merged_df$Salaries.Norm = merged_df$Salaries / mean(merged_df$Salaries)
  merged_df$R.Norm = merged_df$R / mean(merged_df$R)

  return(merged_df)
}

year = 2022
mlb2021 = readInResults2(year)
View(mlb2021)

```

```{r}


mlb2022 = readInResults2(2022)
mlb2021 = readInResults2(2021)
mlb2020 = readInResults2(2020)

combined_df <- data.frame()

# Add rows from df1, df2, and df3 to combined_df
combined_df <- rbind(combined_df, mlb2022)
combined_df <- rbind(combined_df, mlb2021)
combined_df <- rbind(combined_df, mlb2020)

# Print the combined data frame
View(combined_df)
```

```{r}

plot(x = combined_df$Salaries.Norm, y = combined_df$R.Norm,
   xlab = "Salaries (millions)",
   ylab = "Performance by Total Runs",	 
   main = "Salaries vs Performance"
)
abline(lm(combined_df$R.Norm ~ combined_df$Salaries.Norm), col='red')

```

```{r}

model = lm(R.Norm ~ Salaries.Norm, data = combined_df)
summary(model)

# Less correlation as it includes factors which muddle the data
```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```
